# FOUNDATION F: NEURAL NETWORKS FROM SCRATCH

In [90]:
import numpy as np

a = np.array([[1, 2, 3],
              [1, 2, 3]])
b = np.array([4, 5, 6])

c = np.asarray(a, copy=True)
c[-1][0] = 10

print(a)
print(c)

[[1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [10  2  3]]


In [96]:
error = np.array([1, 2, 3, 4])
leaky_deriv = np.array([4, 3, 2, 1])

example = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

np.dot((error*leaky_deriv), example)

array([110, 130, 150])

In [56]:
import numpy as np

class Neuron:
    """Implement single neuron class."""

    def __init__(self, input_size):
        """Initialize neuron entity."""
        self.input_size = input_size
        # self.w = np.random.default_rng().random(self.input_size[-1])
        self.w = [1, 2, 3]
        self.b = np.random.default_rng().random()

    def forward(self, x):
        """Calculate forward pass with activation function."""
        new_vector = np.dot(x, self.w) + 4
        return new_vector

In [57]:
"""Run code."""
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

my_neuron = Neuron((A.shape))

In [62]:
print(my_neuron.input_size)
print(my_neuron.w)
print(my_neuron.forward(A))

(4, 3)
[1, 2, 3]
[18 36 54 72]


In [63]:
vector = my_neuron.forward(A)
max(vector)

np.int64(72)

In [64]:
new_vector = vector * 0.01
new_vector

array([0.18, 0.36, 0.54, 0.72])

In [67]:
np.maximum(vector, new_vector)

array([18., 36., 54., 72.])

In [29]:
np.random.default_rng().random(3)

array([0.4473257 , 0.7759708 , 0.93851491])

**The Core Idea**: A neural network is just a mathematical function that can be represented as a computational graph. The "learning" happens by adjusting the parameters of this function to minimize some error.

### First Small Step

Think about a single neuron - the simplest building block. If you were to implement this from scratch in NumPy (no PyTorch yet), what would be the minimal components you'd need?

Consider:
- What inputs does it take?
- What parameters does it have? 
- What computation does it perform?
- What output does it produce?